// Generated by https://pagedraw.io/pages/13461
import React, { Component } from 'react';
import './baby.css';


class Baby extends Component {
  render() {
    return (
      <div className="baby-baby-0">
          <div className="baby-0">
              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/b5a6/844c/33d29b982b59a17080546fc79e3278a5" className="baby-image-6" /> 
          </div>
          <div className="baby-1">
              <div className="baby-image-0">
                  <div className="baby-1-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/ab56/07e8/4305c7a6107693b53e2c11cc08b1e222" className="baby-image-5" /> 
                  </div>
                  <div className="baby-1-0-1">
                      <div className="baby-price-0">19.99</div>
                  </div>
                  <div className="baby-1-0-2">
                      <div className="baby-1-0-2-0">
                          <div className="baby-1-0-2-0-0">
                              <div className="baby-1-0-2-0-0-0">
                                  <div className="baby-rectangle_2" /> 
                                  <div className="baby-add_to_cart-0">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="baby-image-06">
                  <div className="baby-1-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/2608/3ebf/991396b1c364bcee095424f5603480ee" className="baby-image-4" /> 
                  </div>
                  <div className="baby-1-1-1">
                      <div className="baby-price-00">19.99</div>
                  </div>
                  <div className="baby-1-1-2">
                      <div className="baby-1-1-2-0">
                          <div className="baby-1-1-2-0-0">
                              <div className="baby-1-1-2-0-0-0">
                                  <div className="baby-rectangle_2_" /> 
                                  <div className="baby-add_to_cart-00">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="baby-image-49">
                  <div className="baby-1-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/eaee/514a/3bcceecd68815e5da2cfe276bd508157" className="baby-image-68" /> 
                  </div>
                  <div className="baby-1-2-1">
                      <div className="baby-price-000">19.99</div>
                  </div>
                  <div className="baby-1-2-2">
                      <div className="baby-1-2-2-0">
                          <div className="baby-1-2-2-0-0">
                              <div className="baby-1-2-2-0-0-0">
                                  <div className="baby-rectangle_2_6" /> 
                                  <div className="baby-add_to_cart-000">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="baby-2">
              <div className="baby-image-2">
                  <div className="baby-2-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/a400/ce64/b52c9155f74b5fd4763b4c48878aea7f" className="baby-image-9" /> 
                  </div>
                  <div className="baby-2-0-1">
                      <div className="baby-price-0000">19.99</div>
                  </div>
                  <div className="baby-2-0-2">
                      <div className="baby-2-0-2-0">
                          <div className="baby-2-0-2-0-0">
                              <div className="baby-2-0-2-0-0-0">
                                  <div className="baby-rectangle_2_6-0" /> 
                                  <div className="baby-add_to_cart-0000">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="baby-image-47">
                  <div className="baby-2-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/d0be/84ef/e29644ad13bcb1bf540eaec11d0b043d" className="baby-image-066" /> 
                  </div>
                  <div className="baby-2-1-1">
                      <div className="baby-price-00000">19.99</div>
                  </div>
                  <div className="baby-2-1-2">
                      <div className="baby-2-1-2-0">
                          <div className="baby-2-1-2-0-0">
                              <div className="baby-2-1-2-0-0-0">
                                  <div className="baby-rectangle_2_3" /> 
                                  <div className="baby-add_to_cart-00000">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="baby-image-04">
                  <div className="baby-2-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/e714/37c4/fe9903c8f48886983fc8f831885a04d7" className="baby-image-495" /> 
                  </div>
                  <div className="baby-2-2-1">
                      <div className="baby-price-000001">19.99</div>
                  </div>
                  <div className="baby-2-2-2">
                      <div className="baby-2-2-2-0">
                          <div className="baby-2-2-2-0-0">
                              <div className="baby-2-2-2-0-0-0">
                                  <div className="baby-rectangle_2_6-00" /> 
                                  <div className="baby-add_to_cart-000001">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
export default Baby;