// Generated by https://pagedraw.io/pages/13457
import React from 'react';
import './business.css';


export default class Business extends React.Component {
  render() {
    return (
      <div className="business-business-0">
          <div className="business-0">
              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/4810/c131/8d9359b248042ec6400cf459d86700ea" className="business-image-4" /> 
          </div>
          <div className="business-1">
              <div className="business-image-9">
                  <div className="business-1-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/82ad/62cf/220943e0bec24016166a4efee29ed33b" className="business-image-3" /> 
                  </div>
                  <div className="business-1-0-1">
                      <div className="business-price-0">19.99</div>
                  </div>
                  <div className="business-1-0-2">
                      <div className="business-1-0-2-0">
                          <div className="business-1-0-2-0-0">
                              <div className="business-1-0-2-0-0-0">
                                  <div className="business-rectangle_2" /> 
                                  <div className="business-add_to_cart-0">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="business-image-49">
                  <div className="business-1-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/8645/7569/21c28fa425b42974c208b6fbf4ff045f" className="business-image-2" /> 
                  </div>
                  <div className="business-1-1-1">
                      <div className="business-price-00">19.99</div>
                  </div>
                  <div className="business-1-1-2">
                      <div className="business-1-1-2-0">
                          <div className="business-1-1-2-0-0">
                              <div className="business-1-1-2-0-0-0">
                                  <div className="business-rectangle_2_" /> 
                                  <div className="business-add_to_cart-00">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="business-image-76">
                  <div className="business-1-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/fb1d/92e8/8bf692ed79f80ebd789c1293f69535a4" className="business-image-7" /> 
                  </div>
                  <div className="business-1-2-1">
                      <div className="business-price-000">19.99</div>
                  </div>
                  <div className="business-1-2-2">
                      <div className="business-1-2-2-0">
                          <div className="business-1-2-2-0-0">
                              <div className="business-1-2-2-0-0-0">
                                  <div className="business-rectangle_2_6" /> 
                                  <div className="business-add_to_cart-000">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="business-2">
              <div className="business-image-1">
                  <div className="business-2-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/a531/70d9/cf43153673a1e5440ebe66667610a38b" className="business-image-0" /> 
                  </div>
                  <div className="business-2-0-1">
                      <div className="business-price-0000">19.99</div>
                  </div>
                  <div className="business-2-0-2">
                      <div className="business-2-0-2-0">
                          <div className="business-2-0-2-0-0">
                              <div className="business-2-0-2-0-0-0">
                                  <div className="business-rectangle_2_6-0" /> 
                                  <div className="business-add_to_cart-0000">
                                      ADD TO CART
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="business-image-11">
                  <div className="business-2-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/a80a/0fce/e6860140602d58f48f3e23c95f5f264d" className="business-image-09" /> 
                  </div>
                  <div className="business-2-1-1">
                      <div className="business-price-00000">19.99</div>
                  </div>
                  <div className="business-2-1-2">
                      <div className="business-2-1-2-0">
                          <div className="business-2-1-2-0-0">
                              <div className="business-2-1-2-0-0-0">
                                  <div className="business-rectangle_2_3" /> 
                                  <div className="business-add_to_cart-00000">
                                      ADD TO CART
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="business-image-5">
                  <div className="business-2-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/550d/09cc/6a362e0dfd054cb0f707a7115a0f2fcd" className="business-image-44" /> 
                  </div>
                  <div className="business-2-2-1">
                      <div className="business-price-000000">19.99</div>
                  </div>
                  <div className="business-2-2-2">
                      <div className="business-2-2-2-0">
                          <div className="business-2-2-2-0-0">
                              <div className="business-2-2-2-0-0-0">
                                  <div className="business-rectangle_2_6-00" /> 
                                  <div className="business-add_to_cart-000002">
                                      ADD TO CART
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
