// Generated by https://pagedraw.io/pages/14250
import React from 'react';
import './homereturn.css';


export default class Homereturn extends React.Component {
  render() {
    return (
      <div className="homereturn-homereturn-3">
          <div className="homereturn-0">
              <div className="homereturn-rectangle_2">
                  <div className="homereturn-0-0-0">
                      <div className="homereturn-0-0-0-0">
                          <div className="homereturn-0-0-0-0-0">
                              <div className="homereturn-0-0-0-0-0-0">
                                  <div className="homereturn-5">{"50% OFF"}</div>
                                  <div className="homereturn-all-9">ALL</div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="homereturn-0-0-1">
                      <div className="homereturn-shoes-0">SHOES</div>
                  </div>
              </div>
          </div>
          <div className="homereturn-1">
              <div className="homereturn-rectangle-1">
                  <div className="homereturn-1-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/42d4/d17a/7fcad80381bcf19362136f9ad02ba35a" className="homereturn-image-7" /> 
                  </div>
              </div>
              <div className="homereturn-rectangle-7">
                  <div className="homereturn-1-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/87a6/e2ae/5d0a0a883315f22e37e6bcb2094cbf33" className="homereturn-image_6" /> 
                  </div>
              </div>
              <div className="homereturn-rectangle-6">
                  <div className="homereturn-1-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/15e0/a8ad/4ed625254edcd5bc79a110f9b6649047" className="homereturn-image_8" /> 
                  </div>
              </div>
          </div>
          <div className="homereturn-2">
              <div className="homereturn-rectangle-5">
                  <div className="homereturn-2-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/fc80/767f/781897e10a9ff85e9afc15b23d5b1266" className="homereturn-image_3" /> 
                  </div>
              </div>
              <div className="homereturn-rectangle-53">
                  <div className="homereturn-2-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/fb1d/92e8/8bf692ed79f80ebd789c1293f69535a4" className="homereturn-image_5" /> 
                  </div>
              </div>
              <div className="homereturn-rectangle-4">
                  <div className="homereturn-2-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/e714/37c4/fe9903c8f48886983fc8f831885a04d7" className="homereturn-image_7" /> 
                  </div>
              </div>
          </div>
          <div className="homereturn-3">
              <div className="homereturn-rectangle-0">
                  <div className="homereturn-3-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/e682/b6ab/52f3ac994665314d23c66f743e110d44" className="homereturn-image_2" /> 
                  </div>
              </div>
              <div className="homereturn-rectangle-2">
                  <div className="homereturn-3-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/94cd/bd58/27f97342b926e35ff970a0bbd690c20f" className="homereturn-image_4" /> 
                  </div>
              </div>
              <div className="homereturn-rectangle-17">
                  <div className="homereturn-3-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/3610/bcc5/61c9616ce62e15179b7189e9b9e512f3" className="homereturn-image_9" /> 
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
