// Generated by https://pagedraw.io/pages/14249
import React from 'react';
import './home.css';


export default class Home extends React.Component {
  render() {
    return (
      <div className="home-home-0">
          <div className="home-0">
              <div className="home-rectangle_2">
                  <div className="home-0-0-0">
                      <div className="home-0-0-0-0">
                          <div className="home-0-0-0-0-0">
                              <div className="home-0-0-0-0-0-0">
                                  <div className="home-5">{"50% OFF"}</div>
                                  <div className="home-all-0">ALL</div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="home-0-0-1">
                      <div className="home-shoes-0">SHOES</div>
                  </div>
              </div>
          </div>
          <div className="home-1">
              <div className="home-rectangle-0">
                  <div className="home-1-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/42d4/d17a/7fcad80381bcf19362136f9ad02ba35a" className="home-image-9" /> 
                  </div>
              </div>
              <div className="home-rectangle-00">
                  <div className="home-1-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/87a6/e2ae/5d0a0a883315f22e37e6bcb2094cbf33" className="home-image-7" /> 
                  </div>
              </div>
              <div className="home-rectangle-000">
                  <div className="home-1-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/15e0/a8ad/4ed625254edcd5bc79a110f9b6649047" className="home-image-0" /> 
                  </div>
              </div>
          </div>
          <div className="home-2">
              <div className="home-rectangle-0000">
                  <div className="home-2-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/fc80/767f/781897e10a9ff85e9afc15b23d5b1266" className="home-image-8" /> 
                  </div>
              </div>
              <div className="home-rectangle-00000">
                  <div className="home-2-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/fb1d/92e8/8bf692ed79f80ebd789c1293f69535a4" className="home-image-85" /> 
                  </div>
              </div>
              <div className="home-rectangle-000000">
                  <div className="home-2-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/e714/37c4/fe9903c8f48886983fc8f831885a04d7" className="home-image-5" /> 
                  </div>
              </div>
          </div>
          <div className="home-3">
              <div className="home-rectangle-000002">
                  <div className="home-3-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/e682/b6ab/52f3ac994665314d23c66f743e110d44" className="home-image-6" /> 
                  </div>
              </div>
              <div className="home-rectangle-000001">
                  <div className="home-3-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/94cd/bd58/27f97342b926e35ff970a0bbd690c20f" className="home-image-1" /> 
                  </div>
              </div>
              <div className="home-rectangle-0000005">
                  <div className="home-3-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/3610/bcc5/61c9616ce62e15179b7189e9b9e512f3" className="home-image-89" /> 
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
