// Generated by https://pagedraw.io/pages/13458
import React from 'react';
import './kids.css';


export default class Kids extends React.Component {
  render() {
    return (
      <div className="kids-kids-0">
          <div className="kids-0">
              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/42cc/3670/7ee8160db1b431b96f423d11dcd2b002" className="kids-image-7" /> 
          </div>
          <div className="kids-1">
              <div className="kids-image-2">
                  <div className="kids-1-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/94cd/bd58/27f97342b926e35ff970a0bbd690c20f" className="kids-image-3" /> 
                  </div>
                  <div className="kids-1-0-1">
                      <div className="kids-price-0">19.99</div>
                  </div>
                  <div className="kids-1-0-2">
                      <div className="kids-1-0-2-0">
                          <div className="kids-1-0-2-0-0">
                              <div className="kids-1-0-2-0-0-0">
                                  <div className="kids-rectangle_2" /> 
                                  <div className="kids-add_to_cart-0">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="kids-image-29">
                  <div className="kids-1-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/3610/bcc5/61c9616ce62e15179b7189e9b9e512f3" className="kids-image-21" /> 
                  </div>
                  <div className="kids-1-1-1">
                      <div className="kids-price-00">19.99</div>
                  </div>
                  <div className="kids-1-1-2">
                      <div className="kids-1-1-2-0">
                          <div className="kids-1-1-2-0-0">
                              <div className="kids-1-1-2-0-0-0">
                                  <div className="kids-rectangle_2_" /> 
                                  <div className="kids-add_to_cart-00">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="kids-image-32">
                  <div className="kids-1-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/df7f/59f1/dd711538d30148a8707964054b71efea" className="kids-image-73" /> 
                  </div>
                  <div className="kids-1-2-1">
                      <div className="kids-price-000">19.99</div>
                  </div>
                  <div className="kids-1-2-2">
                      <div className="kids-1-2-2-0">
                          <div className="kids-1-2-2-0-0">
                              <div className="kids-1-2-2-0-0-0">
                                  <div className="kids-rectangle_2_6" /> 
                                  <div className="kids-add_to_cart-000">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="kids-2">
              <div className="kids-image-291">
                  <div className="kids-2-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/64cb/cb45/cbaee8e800a6e75e8ac85cf8019d56a2" className="kids-image-8" /> 
                  </div>
                  <div className="kids-2-0-1">
                      <div className="kids-price-0000">19.99</div>
                  </div>
                  <div className="kids-2-0-2">
                      <div className="kids-2-0-2-0">
                          <div className="kids-2-0-2-0-0">
                              <div className="kids-2-0-2-0-0-0">
                                  <div className="kids-rectangle_2_6-0" /> 
                                  <div className="kids-add_to_cart-0000">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="kids-image-4">
                  <div className="kids-2-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/05ca/e852/f25dba7dcd4c3fce5fa43921c9f17525" className="kids-image-0" /> 
                  </div>
                  <div className="kids-2-1-1">
                      <div className="kids-price-00000">19.99</div>
                  </div>
                  <div className="kids-2-1-2">
                      <div className="kids-2-1-2-0">
                          <div className="kids-2-1-2-0-0">
                              <div className="kids-2-1-2-0-0-0">
                                  <div className="kids-rectangle_2_3" /> 
                                  <div className="kids-add_to_cart-00000">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="kids-image-6">
                  <div className="kids-2-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/f28c/6dd0/8949f42c03d87bcd50236148fa5a9b61" className="kids-image-1" /> 
                  </div>
                  <div className="kids-2-2-1">
                      <div className="kids-price-000003">19.99</div>
                  </div>
                  <div className="kids-2-2-2">
                      <div className="kids-2-2-2-0">
                          <div className="kids-2-2-2-0-0">
                              <div className="kids-2-2-2-0-0-0">
                                  <div className="kids-rectangle_2_6-00" /> 
                                  <div className="kids-add_to_cart-000004">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
