// Generated by https://pagedraw.io/pages/13416
import React, { Component } from 'react';
import './main.css';
import {
    Route,
    NavLink,
    HashRouter
} from "react-router-dom";
  import Mens from "./mens";
  import Womens from "./womens";
  import Kids from "./kids";
  import Baby from "./baby";
  import Sports from "./sports";
  import Business from "./business";

class Main extends Component {
  render() {
    return (
        <HashRouter>
      <div className="main-main-0">
          <div className="main-0">
              <div className="main-top_label-7">
                  <div className="main-0-0-0">
                      <div className="main-0-0-0-0">
                          <div className="main-0-0-0-0-0">
                              <div className="main-logo-7" /> 
                          </div>
                      </div>
                      <div className="main-image-8">
                          <div className="main-0-0-0-1-0">
                              <div className="main-image-4">
                                  <div className="main-0-0-0-1-0-0-0">
                                      <div className="main-rectangle-0">
                                          <div className="main-0-0-0-1-0-0-0-0-0">
                                              <div className="main-login_my_account_my_cart-0">
                                                  Login  /  My Account  /  My Cart
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="main-0-0-0-1-0-0-1">
                                      <div className="main-rectangle_3">
                                          <div className="main-0-0-0-1-0-0-1-0-0">
                                              <div className="main-search-0">SEARCH</div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="main-0-0-1">
                      <div className="main-rectangle_4" /> 
                  </div>
                  <div className="main-0-0-2">
                      <div className="main-image-0">
                          <div className="main-0-0-2-0-0">
                              <div className="main-0-0-2-0-0-0">
                                  <div className="main-0-0-2-0-0-0-0">
                                  <div className="main-mens-0"><NavLink to="/mens.js">MENS</NavLink></div>
                                  </div>
                              </div>
                              <div className="main-0-0-2-0-0-1">
                                  <div className="main-0-0-2-0-0-1-0">
                                      <div className="main-womens-00">
                                          <div className="main-0-0-2-0-0-1-0-0-0">
                                              <div className="main-womens-0"><NavLink to="/womens.js">WOMENS</NavLink></div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="main-0-0-2-0-0-2">
                                  <div className="main-0-0-2-0-0-2-0">
                                      <div className="main-kids-00">
                                          <div className="main-0-0-2-0-0-2-0-0-0">
                                              <div className="main-kids-0"><NavLink to="/kids.js">KIDS</NavLink></div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="main-0-0-2-0-0-3">
                                  <div className="main-0-0-2-0-0-3-0">
                                      <div className="main-baby-00">
                                          <div className="main-0-0-2-0-0-3-0-0-0">
                                              <div className="main-baby-0"><NavLink to="/baby.js">BABY</NavLink></div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="main-0-0-2-0-0-4">
                                  <div className="main-0-0-2-0-0-4-0">
                                      <div className="main-sports-00">
                                          <div className="main-0-0-2-0-0-4-0-0-0">
                                              <div className="main-sports-0"><NavLink to="/sports.js">SPORTS</NavLink></div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="main-0-0-2-0-0-5">
                                  <div className="main-0-0-2-0-0-5-0">
                                      <div className="main-business-00">
                                          <div className="main-0-0-2-0-0-5-0-0-0">
                                              <div className="main-business-0"><NavLink to="/business.js">BUSINESS</NavLink></div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
            <Route path="/mens.js" component={Mens}/>
            <Route path="/womens.js" component={Womens}/>
            <Route path="/kids.js" component={Kids}/>
            <Route path="/baby.js" component={Baby}/>
            <Route path="/sports.js" component={Sports}/>
            <Route path="/business.js" component={Business}/>
          <div className="main-1">
              <div className="main-bottom_label-0">
                  <div className="main-1-0-0">
                      <div className="main-1-0-0-0">
                          <div className="main-1-0-0-0-0">
                              <div className="main-logo-1" /> 
                          </div>
                      </div>
                      <div className="main-rectangle_5">
                          <div className="main-1-0-0-1-0">
                              <div className="main-image-2" /> 
                          </div>
                          <div className="main-1-0-0-1-1">
                              <div className="main-rectangle_6" /> 
                          </div>
                      </div>
                      <div className="main-1-0-0-2">
                          <div className="main-1-0-0-2-0">
                              <div className="main-contact_us-0">CONTACT US</div>
                          </div>
                          <div className="main-1-0-0-2-1">
                              <div className="main-12">
                                  <div>1234 East Coast St.</div>
                                  <div>Neverville, GA</div>
                                  <div>98765</div>
                                  <br/>
                                  <div>1-800-456-7894</div>
                              </div>
                          </div>
                      </div>
                      <div className="main-1-0-0-3">
                          <div className="main-1-0-0-3-0">
                              <div className="main-customer_service-0">
                                  CUSTOMER SERVICE
                              </div>
                          </div>
                          <div className="main-1-0-0-3-1">
                              <div className="main-orders_shipping_account_general-0">
                                  <div>ORDERS</div>
                                  <br/>
                                  <div>SHIPPING</div>
                                  <br/>
                                  <div>ACCOUNT</div>
                                  <br/>
                                  <div>GENERAL</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="main-2" /> 
      </div>
      </HashRouter>
    );
  }
};
export default Main;