// Generated by https://pagedraw.io/pages/13460
import React from 'react';
import './mens.css';


export default class Mens extends React.Component {
  render() {
    return (
      <div className="mens-mens-0">
          <div className="mens-0">
              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/4873/de6f/4b915b0ade1c7e28cd3bcbf664634816" className="mens-image-8" /> 
          </div>
          <div className="mens-1">
              <div className="mens-image-6">
                  <div className="mens-1-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/42d4/d17a/7fcad80381bcf19362136f9ad02ba35a" className="mens-image-1" /> 
                  </div>
                  <div className="mens-1-0-1">
                      <div className="mens-price-0">19.99</div>
                  </div>
                  <div className="mens-1-0-2">
                      <div onClick={this.props.onClick} className="mens-addtocart-0">
                          <div className="mens-1-0-2-0-0">
                              <div className="mens-add_to_cart-0">ADD TO CART</div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="mens-image-61">
                  <div className="mens-1-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/15e0/a8ad/4ed625254edcd5bc79a110f9b6649047" className="mens-image-19" /> 
                  </div>
                  <div className="mens-1-1-1">
                      <div className="mens-price-00">19.99</div>
                  </div>
                  <div className="mens-1-1-2">
                      <div className="mens-rectangle_2">
                          <div className="mens-1-1-2-0-0">
                              <div className="mens-add_to_cart-00">ADD TO CART</div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="mens-image-63">
                  <div className="mens-1-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/998c/68ae/53e427187f534b11bff185a7ea8bc9b4" className="mens-image-9" /> 
                  </div>
                  <div className="mens-1-2-1">
                      <div className="mens-price-000">19.99</div>
                  </div>
                  <div className="mens-1-2-2">
                      <div className="mens-rectangle_2_">
                          <div className="mens-1-2-2-0-0">
                              <div className="mens-add_to_cart-8">ADD TO CART</div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="mens-2">
              <div className="mens-image-62">
                  <div className="mens-2-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/1d5f/116a/4e707f2481fadb5864a89576d6af2c80" className="mens-image-0" /> 
                  </div>
                  <div className="mens-2-0-1">
                      <div className="mens-price-0000">19.99</div>
                  </div>
                  <div className="mens-2-0-2">
                      <div className="mens-rectangle_2_6">
                          <div className="mens-2-0-2-0-0">
                              <div className="mens-add_to_cart-7">ADD TO CART</div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="mens-image-10">
                  <div className="mens-2-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/a531/70d9/cf43153673a1e5440ebe66667610a38b" className="mens-image-12" /> 
                  </div>
                  <div className="mens-2-1-1">
                      <div className="mens-price-00000">19.99</div>
                  </div>
                  <div className="mens-2-1-2">
                      <div className="mens-rectangle_2_3">
                          <div className="mens-2-1-2-0-0">
                              <div className="mens-add_to_cart-3">ADD TO CART</div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="mens-image-60">
                  <div className="mens-2-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/227b/e843/b9c9233f4dfbedec3942e3347f642002" className="mens-image-3" /> 
                  </div>
                  <div className="mens-2-2-1">
                      <div className="mens-price-000003">19.99</div>
                  </div>
                  <div className="mens-2-2-2">
                      <div className="mens-rectangle_2_6-0">
                          <div className="mens-2-2-2-0-0">
                              <div className="mens-add_to_cart-70">ADD TO CART</div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
