// Generated by https://pagedraw.io/pages/13455
import React, { Component } from 'react';
import './sports.css';


class Sports extends Component {
  render() {
    return (
      <div className="sports-sports-0">
          <div className="sports-0">
              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/6797/efd1/4dc0d2d60696119dab1459af9ff0fd1c" className="sports-image-9" /> 
          </div>
          <div className="sports-1">
              <div className="sports-image-99">
                  <div className="sports-1-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/2883/15d2/d12e5c07cbd8615311c9921cf356ae91" className="sports-image-5" /> 
                  </div>
                  <div className="sports-1-0-1">
                      <div className="sports-price-0">19.99</div>
                  </div>
                  <div className="sports-1-0-2">
                      <div className="sports-1-0-2-0">
                          <div className="sports-1-0-2-0-0">
                              <div className="sports-1-0-2-0-0-0">
                                  <div className="sports-rectangle_2" /> 
                                  <div className="sports-add_to_cart-0">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="sports-image-67">
                  <div className="sports-1-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/87a6/e2ae/5d0a0a883315f22e37e6bcb2094cbf33" className="sports-image-6" /> 
                  </div>
                  <div className="sports-1-1-1">
                      <div className="sports-price-00">19.99</div>
                  </div>
                  <div className="sports-1-1-2">
                      <div className="sports-1-1-2-0">
                          <div className="sports-1-1-2-0-0">
                              <div className="sports-1-1-2-0-0-0">
                                  <div className="sports-rectangle_2_" /> 
                                  <div className="sports-add_to_cart-00">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="sports-image-2">
                  <div className="sports-1-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/9701/8d1d/1a85ace7fa3c6da5e65f611854ede33a" className="sports-image-0" /> 
                  </div>
                  <div className="sports-1-2-1">
                      <div className="sports-price-000">19.99</div>
                  </div>
                  <div className="sports-1-2-2">
                      <div className="sports-1-2-2-0">
                          <div className="sports-1-2-2-0-0">
                              <div className="sports-1-2-2-0-0-0">
                                  <div className="sports-rectangle_2_6" /> 
                                  <div className="sports-add_to_cart-000">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="sports-2">
              <div className="sports-image-4">
                  <div className="sports-2-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/347c/8cc5/ce24b0846fae7b98ff6118cc350975f6" className="sports-image-3" /> 
                  </div>
                  <div className="sports-2-0-1">
                      <div className="sports-price-0000">19.99</div>
                  </div>
                  <div className="sports-2-0-2">
                      <div className="sports-2-0-2-0">
                          <div className="sports-2-0-2-0-0">
                              <div className="sports-2-0-2-0-0-0">
                                  <div className="sports-rectangle_2_6-0" /> 
                                  <div className="sports-add_to_cart-0000">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="sports-image-57">
                  <div className="sports-2-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/1a63/5a77/d61b5334eaa8db80c0395d3551dd0724" className="sports-image-62" /> 
                  </div>
                  <div className="sports-2-1-1">
                      <div className="sports-price-00000">19.99</div>
                  </div>
                  <div className="sports-2-1-2">
                      <div className="sports-2-1-2-0">
                          <div className="sports-2-1-2-0-0">
                              <div className="sports-2-1-2-0-0-0">
                                  <div className="sports-rectangle_2_3" /> 
                                  <div className="sports-add_to_cart-00000">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="sports-image-42">
                  <div className="sports-2-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/e682/b6ab/52f3ac994665314d23c66f743e110d44" className="sports-image-03" /> 
                  </div>
                  <div className="sports-2-2-1">
                      <div className="sports-price-000000">19.99</div>
                  </div>
                  <div className="sports-2-2-2">
                      <div className="sports-2-2-2-0">
                          <div className="sports-2-2-2-0-0">
                              <div className="sports-2-2-2-0-0-0">
                                  <div className="sports-rectangle_2_6-00" /> 
                                  <div className="sports-add_to_cart-000002">
                                      ADD TO CART
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
export default Sports;