// Generated by https://pagedraw.io/pages/13453
import React, { Component } from 'react';
import './womens.css';


class Womens extends Component {
  render() {
    return (
      <div className="womens-womens-0">
          <div className="womens-0">
              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/f5c0/6601/7d854db2a727e20a2a98eaedf59f979f" className="womens-image-2" /> 
          </div>
          <div className="womens-1">
              <div className="womens-image-0">
                  <div className="womens-1-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/771a/ac44/2fcc83f8c638ce794881643b0c25199a" className="womens-image-9" /> 
                  </div>
                  <div className="womens-1-0-1">
                      <div className="womens-price-0">19.99</div>
                  </div>
                  <div className="womens-1-0-2">
                      <div className="womens-1-0-2-0">
                          <div className="womens-1-0-2-0-0">
                              <div className="womens-1-0-2-0-0-0">
                                  <div className="womens-rectangle_2" /> 
                                  <div className="womens-add_to_cart-0">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="womens-image-97">
                  <div className="womens-1-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/79fe/9aa1/fa55e1fd69f9a4241ecee8e10c77f41b" className="womens-image-6" /> 
                  </div>
                  <div className="womens-1-1-1">
                      <div className="womens-price-00">19.99</div>
                  </div>
                  <div className="womens-1-1-2">
                      <div className="womens-1-1-2-0">
                          <div className="womens-1-1-2-0-0">
                              <div className="womens-1-1-2-0-0-0">
                                  <div className="womens-rectangle_2_" /> 
                                  <div className="womens-add_to_cart-00">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="womens-image-06">
                  <div className="womens-1-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/2a7d/efa1/8ffe7e6f676fe8db221d40446b18ab31" className="womens-image-62" /> 
                  </div>
                  <div className="womens-1-2-1">
                      <div className="womens-price-000">19.99</div>
                  </div>
                  <div className="womens-1-2-2">
                      <div className="womens-1-2-2-0">
                          <div className="womens-1-2-2-0-0">
                              <div className="womens-1-2-2-0-0-0">
                                  <div className="womens-rectangle_2_6" /> 
                                  <div className="womens-add_to_cart-000">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="womens-2">
              <div className="womens-image-45">
                  <div className="womens-2-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/fb1d/92e8/8bf692ed79f80ebd789c1293f69535a4" className="womens-image-4" /> 
                  </div>
                  <div className="womens-2-0-1">
                      <div className="womens-price-0000">19.99</div>
                  </div>
                  <div className="womens-2-0-2">
                      <div className="womens-2-0-2-0">
                          <div className="womens-2-0-2-0-0">
                              <div className="womens-2-0-2-0-0-0">
                                  <div className="womens-rectangle_2_6-0" /> 
                                  <div className="womens-add_to_cart-0000">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="womens-image-56">
                  <div className="womens-2-1-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/b37d/07cf/5092a889bd46f76dca1b214d971c7f9a" className="womens-image-5" /> 
                  </div>
                  <div className="womens-2-1-1">
                      <div className="womens-price-00000">19.99</div>
                  </div>
                  <div className="womens-2-1-2">
                      <div className="womens-2-1-2-0">
                          <div className="womens-2-1-2-0-0">
                              <div className="womens-2-1-2-0-0-0">
                                  <div className="womens-rectangle_2_3" /> 
                                  <div className="womens-add_to_cart-00000">ADD TO CART</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="womens-image-75">
                  <div className="womens-2-2-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/832a/1772/0a5def129dfb2be1355f80e5dfcf731f" className="womens-image-7" /> 
                  </div>
                  <div className="womens-2-2-1">
                      <div className="womens-price-000000">19.99</div>
                  </div>
                  <div className="womens-2-2-2">
                      <div className="womens-2-2-2-0">
                          <div className="womens-2-2-2-0-0">
                              <div className="womens-2-2-2-0-0-0">
                                  <div className="womens-rectangle_2_6-00" /> 
                                  <div className="womens-add_to_cart-000002">
                                      ADD TO CART
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
export default Womens;